//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Учет_работы_мастерских
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipments_In_Workshop
    {
        public int id_equipment_in_workshop { get; set; }
        public int id_workshop { get; set; }
        public int id_equipment { get; set; }
    
        public virtual equipments equipments { get; set; }
        public virtual workshops workshops { get; set; }
    }
}
